version: "3.3"
services:
  web:
    build: ./frontend
    ports:
    - target: 80
      published: 80 # note: cybera use port 80
      protocol: tcp # default
      mode: host # default

  django:
    build: ./backend
    ports:
    - "8000:8000"